<a href="https://colab.research.google.com/github/clerfayt28/Pitonchik/blob/main/PyTorch_Tutorial_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [2]:
''' 3 DIFFERENT METHODS TO REMEMBER:
 - torch.save(arg, PATH) # can be model, tensor, or dictionary
 - torch.load(PATH)
 - torch.load_state_dict(arg)
'''

''' 2 DIFFERENT WAYS OF SAVING
# 1) lazy way: save whole model
torch.save(model, PATH)

# model class must be defined somewhere
model = torch.load(PATH)
model.eval()

# 2) recommended way: save only the state_dict
torch.save(model.state_dict(), PATH)

# model must be created again with parameters
model = Model(*args, **kwargs)
model.load_state_dict(torch.load(PATH))
model.eval()
'''

' 2 DIFFERENT WAYS OF SAVING\n# 1) lazy way: save whole model\ntorch.save(model, PATH)\n\n# model class must be defined somewhere\nmodel = torch.load(PATH)\nmodel.eval()\n\n# 2) recommended way: save only the state_dict\ntorch.save(model.state_dict(), PATH)\n\n# model must be created again with parameters\nmodel = Model(*args, **kwargs)\nmodel.load_state_dict(torch.load(PATH))\nmodel.eval()\n'

In [4]:
class Model(nn.Module):
    def __init__(self, n_input_features):
        super(Model, self).__init__()
        self.linear = nn.Linear(n_input_features, 1)

    def forward(self, x):
        y_pred = torch.sigmoid(self.linear(x))
        return y_pred

model = Model(n_input_features=6)
# train your model...

In [5]:
# save all #
for param in model.parameters():
    print(param)

# save and load entire model

FILE = "model.pth"
torch.save(model, FILE)

loaded_model = torch.load(FILE)
loaded_model.eval()

for param in loaded_model.parameters():
    print(param)

# save only state dict #

FILE = "model.pth"
torch.save(model.state_dict(), FILE)

print(model.state_dict())
loaded_model = Model(n_input_features=6)
loaded_model.load_state_dict(torch.load(FILE)) # it takes the loaded dictionary, not the path file itself
loaded_model.eval()

print(loaded_model.state_dict())


# load checkpoint #
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

checkpoint = {
"epoch": 90,
"model_state": model.state_dict(),
"optim_state": optimizer.state_dict()
}
print(optimizer.state_dict())
FILE = "checkpoint.pth"
torch.save(checkpoint, FILE)

model = Model(n_input_features=6)
optimizer = torch.optim.SGD(model.parameters(), lr=0)

checkpoint = torch.load(FILE)
model.load_state_dict(checkpoint['model_state'])
optimizer.load_state_dict(checkpoint['optim_state'])
epoch = checkpoint['epoch']

model.eval()
# - or -
# model.train()

print(optimizer.state_dict())

Parameter containing:
tensor([[-0.4068,  0.0106,  0.2854,  0.3078, -0.0396,  0.2419]],
       requires_grad=True)
Parameter containing:
tensor([-0.2289], requires_grad=True)
Parameter containing:
tensor([[-0.4068,  0.0106,  0.2854,  0.3078, -0.0396,  0.2419]],
       requires_grad=True)
Parameter containing:
tensor([-0.2289], requires_grad=True)
OrderedDict([('linear.weight', tensor([[-0.4068,  0.0106,  0.2854,  0.3078, -0.0396,  0.2419]])), ('linear.bias', tensor([-0.2289]))])
OrderedDict([('linear.weight', tensor([[-0.4068,  0.0106,  0.2854,  0.3078, -0.0396,  0.2419]])), ('linear.bias', tensor([-0.2289]))])
{'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'params': [0, 1]}]}
{'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'params': [0, 